function build_reaction_wheel_pid_validation_model()
%BUILD_REACTION_WHEEL_PID_VALIDATION_MODEL Build a Simulink PID validation model.
%
% The generated model mirrors the embedded controller in
% src/ReactionWheelController.cpp: error = pitch - targetPitch, derivative uses
% pitch rate, output is signed PWM,
% output is saturated to +/-255, commands slew by 32 counts per 5 ms loop,
% and nonzero commands are raised to the motor's minimum active PWM.

model = "reaction_wheel_pid_validation";
if bdIsLoaded(model)
    close_system(model, 0);
end

Ts = 0.005;
targetPitch = 1.150;
initialPitchError = 0.08;
initialPitchRate = 0.0;
simStopTime = 5.0;

Kp = 5300.0;
Ki = 30.0;
Kd = 650.0;
maxPwm = 255;
minActivePwm = 90;
maxCommandStepPerCycle = 32;
balanceDeadbandRad = 0.015;
rateDeadbandRps = 0.08;

bodyMomentOfInertiaKgM2 = 0.000375;
totalBodyMassWithWheelKg = 0.271;
comDistanceToPivotM = 0.0517;
gravityMps2 = 9.81;
motorStallTorqueGcm = 714.0;
gramCmToNm = 0.0000980665;
motorStallCurrentA = 10.0;
motorCurrentLimitA = 2.0;
estimatedMaxMotorTorqueNm = motorStallTorqueGcm * gramCmToNm * ...
    (motorCurrentLimitA / motorStallCurrentA);
torquePerPwm = estimatedMaxMotorTorqueNm / maxPwm;

assignin("base", "Ts", Ts);
assignin("base", "targetPitch", targetPitch);
assignin("base", "initialPitchError", initialPitchError);
assignin("base", "initialPitchRate", initialPitchRate);
assignin("base", "Kp", Kp);
assignin("base", "Ki", Ki);
assignin("base", "Kd", Kd);
assignin("base", "maxPwm", maxPwm);
assignin("base", "minActivePwm", minActivePwm);
assignin("base", "maxCommandStepPerCycle", maxCommandStepPerCycle);
assignin("base", "balanceDeadbandRad", balanceDeadbandRad);
assignin("base", "rateDeadbandRps", rateDeadbandRps);
assignin("base", "bodyMomentOfInertiaKgM2", bodyMomentOfInertiaKgM2);
assignin("base", "totalBodyMassWithWheelKg", totalBodyMassWithWheelKg);
assignin("base", "comDistanceToPivotM", comDistanceToPivotM);
assignin("base", "gravityMps2", gravityMps2);
assignin("base", "torquePerPwm", torquePerPwm);

new_system(model);
open_system(model);
set_param(model, ...
    "StopTime", num2str(simStopTime), ...
    "Solver", "ode4", ...
    "FixedStep", "Ts", ...
    "SaveOutput", "on", ...
    "ReturnWorkspaceOutputs", "on");

add_block("simulink/Sources/Constant", model + "/initial pitch error", ...
    "Value", "initialPitchError", "Position", [35 70 135 100]);
add_block("simulink/Sources/Constant", model + "/initial pitch rate", ...
    "Value", "initialPitchRate", "Position", [35 145 135 175]);

add_block("simulink/Discrete/Discrete-Time Integrator", model + "/error integral", ...
    "SampleTime", "Ts", "InitialCondition", "0", ...
    "LimitOutput", "on", ...
    "UpperSaturationLimit", "1", "LowerSaturationLimit", "-1", ...
    "Position", [235 255 300 295]);
add_block("simulink/Math Operations/Gain", model + "/Kp", ...
    "Gain", "Kp", "Position", [235 65 285 105]);
add_block("simulink/Math Operations/Gain", model + "/Ki", ...
    "Gain", "Ki", "Position", [335 255 385 295]);
add_block("simulink/Math Operations/Gain", model + "/Kd", ...
    "Gain", "Kd", "Position", [235 145 285 185]);
add_block("simulink/Math Operations/Sum", model + "/pid sum", ...
    "Inputs", "+++", "Position", [440 110 465 180]);
add_block("simulink/Discontinuities/Saturation", model + "/pid saturation", ...
    "UpperLimit", "maxPwm", "LowerLimit", "-maxPwm", ...
    "Position", [515 125 585 165]);
add_block("simulink/User-Defined Functions/MATLAB Function", model + "/firmware command shaping", ...
    "Position", [635 105 800 185]);
setMatlabFunctionScript(model + "/firmware command shaping", firmwareCommandScript());

add_block("simulink/Math Operations/Gain", model + "/PWM to reaction torque", ...
    "Gain", "torquePerPwm", "Position", [850 125 955 165]);
add_block("simulink/User-Defined Functions/MATLAB Function", model + "/reaction wheel plant", ...
    "Position", [1010 85 1185 205]);
setMatlabFunctionScript(model + "/reaction wheel plant", plantScript());

add_block("simulink/Sinks/To Workspace", model + "/pitch_error", ...
    "VariableName", "pitch_error", "SaveFormat", "Timeseries", ...
    "Position", [1250 70 1350 100]);
add_block("simulink/Sinks/To Workspace", model + "/pitch_rate", ...
    "VariableName", "pitch_rate", "SaveFormat", "Timeseries", ...
    "Position", [1250 140 1350 170]);
add_block("simulink/Sinks/To Workspace", model + "/motor_pwm", ...
    "VariableName", "motor_pwm", "SaveFormat", "Timeseries", ...
    "Position", [850 220 950 250]);
add_block("simulink/Sinks/Scope", model + "/Scope", ...
    "Position", [1250 230 1355 315]);

add_line(model, "reaction wheel plant/1", "Kp/1");
add_line(model, "reaction wheel plant/1", "error integral/1");
add_line(model, "reaction wheel plant/1", "pitch_error/1");
add_line(model, "reaction wheel plant/1", "Scope/1");
add_line(model, "reaction wheel plant/2", "Kd/1");
add_line(model, "reaction wheel plant/2", "pitch_rate/1");
add_line(model, "reaction wheel plant/2", "Scope/2");
add_line(model, "Kp/1", "pid sum/1");
add_line(model, "Ki/1", "pid sum/2");
add_line(model, "Kd/1", "pid sum/3");
add_line(model, "error integral/1", "Ki/1");
add_line(model, "pid sum/1", "pid saturation/1");
add_line(model, "pid saturation/1", "firmware command shaping/1");
add_line(model, "reaction wheel plant/1", "firmware command shaping/2");
add_line(model, "reaction wheel plant/2", "firmware command shaping/3");
add_line(model, "firmware command shaping/1", "PWM to reaction torque/1");
add_line(model, "firmware command shaping/1", "motor_pwm/1");
add_line(model, "firmware command shaping/1", "Scope/3");
add_line(model, "PWM to reaction torque/1", "reaction wheel plant/1");
add_line(model, "initial pitch error/1", "reaction wheel plant/2");
add_line(model, "initial pitch rate/1", "reaction wheel plant/3");

save_system(model, model + ".slx");

simOut = sim(model);
pitchError = simOut.pitch_error;
finalError = pitchError.Data(end);
maxAbsError = max(abs(pitchError.Data));

fprintf("Built %s.slx\n", model);
fprintf("Final pitch error: %.5f rad\n", finalError);
fprintf("Max abs pitch error: %.5f rad\n", maxAbsError);
end

function setMatlabFunctionScript(blockPath, scriptText)
rt = sfroot;
chart = rt.find("-isa", "Stateflow.EMChart", "Path", blockPath);
chart.Script = scriptText;
end

function scriptText = firmwareCommandScript()
scriptText = [
"function pwmOut = fcn(pidOut, pitchError, pitchRate)" newline ...
"%#codegen" newline ...
"persistent rampedCommand" newline ...
"if isempty(rampedCommand)" newline ...
"    rampedCommand = 0;" newline ...
"end" newline ...
"if abs(pitchError) < balanceDeadbandRad && abs(pitchRate) < rateDeadbandRps" newline ...
"    rampedCommand = 0;" newline ...
"    pwmOut = 0;" newline ...
"    return;" newline ...
"end" newline ...
"targetCommand = round(pidOut);" newline ...
"targetCommand = min(max(targetCommand, -maxPwm), maxPwm);" newline ...
"delta = targetCommand - rampedCommand;" newline ...
"delta = min(max(delta, -maxCommandStepPerCycle), maxCommandStepPerCycle);" newline ...
"rampedCommand = rampedCommand + delta;" newline ...
"if rampedCommand == 0" newline ...
"    pwmOut = 0;" newline ...
"elseif rampedCommand > 0" newline ...
"    pwmOut = min(max(rampedCommand, minActivePwm), maxPwm);" newline ...
"else" newline ...
"    pwmOut = -min(max(abs(rampedCommand), minActivePwm), maxPwm);" newline ...
"end" newline ...
"end" newline ...
];
end

function scriptText = plantScript()
scriptText = [
"function [pitchError, pitchRate] = fcn(motorTorque, initialError, initialRate)" newline ...
"%#codegen" newline ...
"persistent x v initialized" newline ...
"if isempty(initialized)" newline ...
"    x = initialError;" newline ...
"    v = initialRate;" newline ...
"    initialized = true;" newline ...
"end" newline ...
"gravityAccel = (totalBodyMassWithWheelKg * gravityMps2 * comDistanceToPivotM / bodyMomentOfInertiaKgM2) * sin(x);" newline ...
"motorAccel = -motorTorque / bodyMomentOfInertiaKgM2;" newline ...
"a = gravityAccel + motorAccel;" newline ...
"v = v + Ts * a;" newline ...
"x = x + Ts * v;" newline ...
"pitchError = x;" newline ...
"pitchRate = v;" newline ...
"end" newline ...
];
end
